[package]
name = "bct-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bct.path = "../bct"

[[bin]]
name = "bct"
path = "src/main.rs"
