[package]
name = "bcts-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
bcts.path = "../bcts"

[[bin]]
name = "bcts"
path = "src/main.rs"
